name: Status Check

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Pull Request Checks"]
    types:
      - completed

jobs:
  status-check:
    name: Check Workflow Status
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'

    steps:
    - name: Check workflow status
      run: |
        echo "Workflow ${{ github.event.workflow_run.name }} failed with conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Please check the workflow logs for details."
        exit 1
